[package]
name = "pts"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.31", features = ["serde"] }
clap = { version = "4.4.3", features = ["derive"] }
colored = "2.0.4"
emojis = "0.6.1"
encoding_rs = "0.8.33"
serde = { version = "1.0.188", features = ["derive"] }
serde-xml-rs = "0.6.0"
