[package]
name = "pts"
version = "0.6.1"
edition = "2021"

[dependencies]
chrono = { version = "0.4.35", features = ["serde"] }
clap = { version = "4.4.3", features = ["derive"] }
colored = "2.0.4"
emojis = "0.6.1"
encoding_rs = "0.8.33"
serde = { version = "1.0.188", features = ["derive"] }
serde-xml-rs = "0.6.0"
serde_json = "1.0.108"
csv = "1.3.0"
